### ISSUE TITLE
Populate daily tables - bills + bill history + vote results

### ISSUE THREAD

**Issue by jessiclassy** [techequitycollaborative/ca-leg-tracker#6]
- [ ] extract new bills that got to "1st reading" status or beyond by the current date
- [ ] extract updates for bills that exist in the DB already
- [ ] extract new vote results by the current date
- [ ] validate bill info and vote results against leginfo.ca.gov
- [ ] test that `bill`, `bill_history`, `*_vote_result` tables can be populated locally
- [ ] configure DO droplet for daily scheduling

**Comment by mvbrooks** [comment]
https://github.com/techequitycollaborative/ca-leg-tracker/pull/13
